# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

CONFIG_BT_DEVICE_NAME="nerdboard"

CONFIG_ZMK_SPLIT=y

# Trackball disabled temporarily for debugging
# CONFIG_ZMK_MOUSE=y
# CONFIG_SPI=y
# CONFIG_PMW3389=y
