
CONFIG_ZMK_DISPLAY=y
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILTIN=y

# Forces this firmware instance to act as a master/central device
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Keeps the display logging engine awake even if disconnected from a partner half
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
